#!/bin/sh

EXT=".js"
DIRNAME=$(dirname $0)

n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local

if [ `whoami` != "root" ]
then
    # echo "Performing sudo - I need root to edit your hosts file."
    # The above message is included if anyone wants it, but it got annoying.
    sudo $0 $*
    exit $?
fi

$DIRNAME/get-shit-done$EXT $*
